config/routes.rb
Rails.application.routes.draw do
  get "orders/show"
  get "carts/show"

  namespace :admin do
    get "orders/index"
    resources :products, except: [:show]
    resources :orders, only: [:index, :show]
  end  

  resource :cart do
    post 'add_item', on: :collection
    post 'checkout', on: :collection
    delete 'remove_item/:id', to: 'carts#remove_item', as: :remove_item
  end

  resources :orders, only: [:show]

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  delete "logout", to: "sessions#destroy"

  resources :products, only: [:show] do
    resources :reviews, only: [:create]  # Вкладений маршрут для створення відгуку
  end

  root to: "main#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  belongs_to :user, optional: true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
  belongs_to :order, optional: true 
  
  validates :quantity, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, optional: true
  has_many :order_items, dependent: :destroy
  has_many :products, through: :order_items

  validates :total_price, presence: true
  validates :status, presence: true, inclusion: { in: %w[pending completed canceled], message: "%{value} is not a valid status" }
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  validates :quantity, presence: true#, numericality: { greater_than: 0 }
  #validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :carts, through: :cart_items
  has_many :reviews, dependent: :destroy
  has_many :users, through: :reviews
  has_many :order_items, dependent: :destroy
  has_one_attached :image
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :product
end

app/models/user.rb
# email:string
# password_digest:string
#
# passwrd:string virtual
# password_confirmation virtualpa

class User < ApplicationRecord
  # Secure password
  has_secure_password

  # Associations
  has_one :cart, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :products, through: :reviews

  def admin?
    admin == true
  end

  # Validations
  validates :email, presence: true, 
                    uniqueness: true, 
                    format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "must be a valid e-mail address" }
end

  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :user_signed_in?, :current_cart

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def user_signed_in?
    current_user.present?
  end

  def current_cart
    if user_signed_in?
      current_user.cart || current_user.create_cart
    else
      Cart.find_or_create_by(user_id: nil)
    end
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart

  def current_cart
    if user_signed_in?
      @current_cart ||= Cart.find_or_create_by(user: current_user)
    else
      session[:cart_id] ||= Cart.create.id
      @current_cart ||= Cart.find(session[:cart_id])
    end
  end  

  def checkout
    @cart_items = current_cart.cart_items
  
    if @cart_items.any?
      total_price = @cart_items.sum { |item| item.quantity * item.product.price }
      order = Order.create(
        user: current_user, # Може бути nil для гостей
        total_price: total_price,
        status: 'pending'
      )
  
      @cart_items.each do |cart_item|
        order.order_items.create(
          product: cart_item.product,
          quantity: cart_item.quantity,
          price: cart_item.product.price
        )
      end
  
      @cart_items.destroy_all # Очищення кошика
      session[:cart_id] = nil # Очистити сесію для гостей
      redirect_to order_path(order), notice: "Order successfully placed!"
    else
      redirect_to cart_path, alert: "Your cart is empty!"
    end
  end
  
  def show
    @cart = current_cart
    @cart_items = current_cart.cart_items.includes(:product)
  end

  def add_item
    product = Product.find(params[:product_id])
    @cart = current_cart
    cart_item = @cart.cart_items.find_by(product: product)
  
    if cart_item
      cart_item.quantity += params[:quantity].to_i
    else
      cart_item = @cart.cart_items.new(product: product, quantity: params[:quantity])
    end
  
    if cart_item.save
      redirect_to cart_path, notice: "#{product.name} додано до кошика!"
    else
      redirect_to product_path(product), alert: "Не вдалося додати товар до кошика."
    end
  end
  
  def remove_item
    cart_item = @cart.cart_items.find_by(id: params[:id])
    if cart_item
      cart_item.destroy
      redirect_to cart_path, notice: "Item removed from cart."
    else
      redirect_to cart_path, alert: "Item not found."
    end
  end

  def destroy
    current_cart.destroy
    redirect_to root_path, notice: "Кошик очищено."
  end

  private

  def set_cart
    @cart = current_cart
  end
  
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @user = current_user
    @products = Product.all
    @cart = current_user ? current_user.cart : Cart.find_or_create_by(user_id: nil) # Use guest cart if not logged in
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: :show

  def show
    redirect_to cart_path
  end

  def create
    @order = current_user.orders.new(order_params)
    @cart = current_cart

    # Копіюємо елементи кошика до замовлення
    @cart.cart_items.each do |cart_item|
      @order.order_items.build(
        product: cart_item.product,
        quantity: cart_item.quantity,
        price: cart_item.product.price
      )
    end

    if @order.save
      @cart.destroy # очищаємо кошик після створення замовлення
      redirect_to cart_path, notice: "Замовлення успішно створено!"
    else
      render :new, alert: "Не вдалося створити замовлення."
    end
  end

  def index
    @orders = current_user.orders.includes(:order_items)
  end

  private

  def set_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:address, :phone_number)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def show
    @product = Product.find(params[:id])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Successfully signed up!"
    else
      render :new, alert: "There was a problem with your registration."
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_product

  def create
    @review = @product.reviews.build(review_params)
    @review.user = current_user

    if @review.save
      redirect_to product_path(@product), notice: 'Review added successfully.'
    else
      redirect_to product_path(@product), alert: 'Failed to add review.'
    end
  end

  private

  def set_product
    @product = Product.find(params[:product_id])
  end

  def review_params
    params.require(:review).permit(:content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  def new

  end

  def create
    user = User.find_by(email: params[:email])
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      session[:admin] = user.admin? 
      redirect_to root_path
    else
      flash[:alert] = "Неправельний email або пароль"
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "First" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">H-hour</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <% if session[:user_id] %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Профіль
            </a>
            <ul class="dropdown-menu">  
              <li><a class="dropdown-item" href="#">Налаштування</a></li>
              <li><%= button_to "Вийти з акаунту", logout_path, method: :delete, class: 'dropdown-item' %></li>
            </ul>
          </li>
          <% if User.find(session[:user_id]).admin? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Адмін-панель
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Товари", admin_products_path, class: "dropdown-item" %></li>
                <li><%= link_to "Замовлення", admin_orders_path, class: "dropdown-item" %></li>
              </ul>
              
            </li>
          <% end %>
        <% else %>  
          <li class="nav-item">
            <a class="nav-link" href="/sign_in">
              Увійти
            </a>
          </li> 
        <% end %>
        <li class="nav-item">
          <%= link_to "Кошик (#{@cart&.cart_items&.sum(:quantity) || 0})", cart_path, class: "nav-link" %>

        </li>


      </ul>
    </div>
  </div>
</nav>