config/routes.rb
Rails.application.routes.draw do
  get "orders/show"
  get "carts/show"

  namespace :admin do
    get "orders/index"
    resources :products, except: [:show]
    resources :orders, only: [:index, :show]
  end  

  resource :cart do
    post 'add_item', on: :collection
    post 'checkout', on: :collection
    delete 'remove_item/:id', to: 'carts#remove_item', as: :remove_item
  end

  resources :orders, only: [:show]

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  delete "logout", to: "sessions#destroy"

  resources :products, only: [:show] do
    resources :reviews, only: [:create]  # Вкладений маршрут для створення відгуку
  end

  root to: "main#index"
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :carts, through: :cart_items
  has_many :reviews, dependent: :destroy
  has_many :users, through: :reviews
  has_many :order_items, dependent: :destroy
  has_one_attached :image
end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < ApplicationController
    before_action :ensure_admin  # Перевірка, чи є користувач адміністратором
    before_action :set_product, only: [:edit, :update, :destroy]

    def index
      @products = Product.all
    end

    def new
      @product = Product.new
    end

    def create
      @product = Product.new(product_params)
      if @product.save
        redirect_to admin_products_path, notice: "Product created successfully."
      else
        flash.now[:alert] = "Failed to create product."
        render :new
      end
    end

    def edit
    end

    def update
      if @product.update(product_params)
        redirect_to admin_products_path, notice: "Product updated successfully."
      else
        flash.now[:alert] = "Failed to update product."
        render :edit
      end
    end

    def destroy
      if @product.present?
        ActiveRecord::Base.transaction do
          @product.cart_items.destroy_all
          @product.order_items.destroy_all
          @product.destroy
        end
        redirect_to admin_products_path, notice: "Product deleted successfully."
      else
        redirect_to admin_products_path, alert: "Product not found."
      end
    end

    private

    def ensure_admin
      redirect_to root_path, alert: "Access denied!" unless session[:admin]
    end

    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :description, :price, :image, :category)
    end
    
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/views/products/show.html.erb
<div>
    <div class="container">
        <% if @product.image.attached? %>
            <%= image_tag @product.image, class: "img-fluid" %>
        <% else %>
            <p>No Image Available</p>
        <% end %>

        <h1><%= @product.name %></h1>
        <h5><%= number_to_currency(@product.price, unit: "₴") %></h5>

        <%= button_to 'Додати до кошика', add_item_cart_path(product_id: @product.id, quantity: 1), method: :post, class: 'btn btn-primary' %>

        <p><%= @product.description %></p>

        <% if user_signed_in? %>
            <h3>Залишити відгук</h3>
            <%= form_with model: [ @product, @product.reviews.new ], local: true do |form| %>
                <div class="form-group">
                    <%= form.label :content, "Ваш відгук" %>
                    <%= form.text_area :content, class: "form-control", rows: 4 %>
                </div>
                <%= form.submit "Відправити", class: "btn btn-primary" %>
            <% end %>
        <% end %>

        <h3>Відгуки:</h3>
        <% if !user_signed_in? %>
            <p>Щоб залишити відгук потрібно увійти в акаунт</p>
        <% end %>
        <% @product.reviews.each do |review| %>
            <div class="review mb-3">
                <% if review.user %>
                    <p><strong><%= review.user.email %></strong></p>
                <% else %>
                    <p><strong>Guest</strong></p>
                <% end %>
                <p><%= review.content %></p>
            </div>
        <% end %>
    </div>
</div>